version: '3.4'
networks:
  tickets-dev:
    driver: bridge
services:
  tickets.webapi:
    image: ${DOCKER_REGISTRY-}ticketswebapi
    build:
      context: .
      dockerfile: Tickets.WebAPI/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    environment:
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "password"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
      ConnectionStrings__DefaultConnection: "Server=postgres_db;Port=5432;User id=postgres;password=admin;database=tickets"
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
        - tickets-dev
    depends_on:
        - postgres_db
    
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "tickets"
    restart: always
    ports:
        - "5433:5432"
    networks:
        - tickets-dev
    volumes:
        - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
     